project:
  type: website
  output-dir: _site

website:
  title: "Bienvenue sur Opubliq"
  sidebar:
    style: "docked"
    logo: "images/logo.png"
    tools:
      - icon: twitter
        href: https://twitter.com/HubCadieux25
      - icon: linkedin
        href: https://www.linkedin.com/in/hubert-cadieux-7172571a0
      - icon: github
        href: https://github.com/hubcad25
      - text: '{{< iconify academicons:google-scholar >}}'
        href: https://scholar.google.com/citations?user=VF6HfPoAAAAJ&hl=fr&oi=ao
    search: true
    type: "dark"
    collapse-level: 1
    contents:
      - text: "Accueil"
        href: index.qmd